name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.package }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    permissions:
      actions: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.12'
          - 'pre'
        os:
          - ubuntu-latest
        arch:
          - x64
        package:
          - BayesDensityCore
          - BayesDensityBSplineMixture
          - BayesDensityFiniteGaussianMixture
          - BayesDensityHistSmoother
          - BayesDensityPitmanYorMixture
          # add more packages here as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v2

      - name: Instantiate and test ${{ matrix.package }}
        run: |
          julia --project=. -e '
            import Pkg
            Pkg.instantiate()
            Pkg.test("${{ matrix.package }}"; coverage=true)
          '

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: lcov.info