name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      # Expose matched filters as job 'packages' output variable
      packages: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          BayesDensityBSplineMixture:
            - BayesDensityCore/**
            - lib/BayesDensityBSplineMixture/**
          BayesDensityCore:
            - BayesDensityCore/**
          BayesDensityFiniteGaussianMixture:
            - BayesDensityCore/**
            - lib/BayesDensityFiniteGaussianMixture/**
          BayesDensityHistSmoother:
            - BayesDensityCore/**
            - lib/BayesDensityHistSmoother/**
          BayesDensityPitmanYorMixture:
            - BayesDensityCore/**
            - lib/BayesDensityPitmanYorMixture/**
          BayesDensityRandomBernsteinPoly:
            - BayesDensityCore/**
            - lib/BayesDensityRandomBernsteinPoly/**
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ matrix.package }}
    runs-on: ${{ matrix.os }}
    needs: changes
    if: needs.changes.outputs.packages != '[]'

    permissions:
      actions: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.12'
          - 'pre'
        os:
          - ubuntu-latest
        arch:
          - x64
        package: ${{ fromJSON(needs.changes.outputs.packages) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Cache Julia artifacts
        uses: julia-actions/cache@v3

      - name: Instantiate and test ${{ matrix.package }}
        run: |
          julia --project=. -e '
            import Pkg
            Pkg.instantiate()
            Pkg.test("${{ matrix.package }}"; coverage=true)
          '

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
        with:
          directories: lib/${{matrix.package}}/src
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: lcov.info